# Generated by Django 4.1.3 on 2022-12-04 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('c_code', models.CharField(default=None, max_length=50, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=50, null=True)),
                ('c_semester', models.CharField(max_length=30, null=True)),
                ('c_credit', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50, null=True)),
                ('student_mailid', models.EmailField(max_length=254, null=True)),
                ('student_PRN', models.CharField(max_length=50, null=True)),
                ('student_branch', models.CharField(max_length=30, null=True)),
                ('student_year', models.CharField(max_length=30, null=True)),
                ('student_semester', models.CharField(max_length=30, null=True)),
                ('student_phno', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('t_id', models.IntegerField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(blank=True, max_length=50, null=True)),
                ('t_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('t_phno', models.CharField(blank=True, max_length=30, null=True)),
                ('t_Gender', models.CharField(blank=True, max_length=50, null=True)),
                ('t_Occupation', models.CharField(max_length=50, null=True)),
                ('t_branch', models.CharField(blank=True, max_length=50, null=True)),
                ('t_post', models.CharField(blank=True, max_length=50, null=True)),
                ('t_DOB', models.DateField(blank=True, max_length=50, null=True)),
                ('tid_name', models.CharField(blank=True, max_length=50, null=True)),
                ('tid_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='course_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('c_teacher', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='c_teacher',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='app.teacher'),
        ),
    ]
